server-name:My Test Server
motd:Hello World!
heartbeat-url:http://localhost:3000/api/v1/heartbeat
world-size:normal
world-height:normal
login-timeout-ms:15000
max-pending-logins:16
max-connections-per-ip:8
auth:local
auth-grace-period-seconds:30
max-accounts:4096
