server-name:My Test Server
motd:Hello World!
heartbeat-url:http://localhost:3000/api/v1/heartbeat
world-size:normal
world-height:normal
login-timeout-ms:15000
max-pending-logins:16
max-connections-per-ip:8
max-players-saved:1024
max-policy-records:4096
